name: trackstatus_flutter
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1 
  cloud_firestore: ^6.0.0

  cupertino_icons: ^1.0.8
  flutter_lints: ^6.0.0
  go_router: ^16.0.0
  font_awesome_flutter: '>= 4.7.0'
  mobile_scanner: ^7.0.1
  pretty_qr_code: ^3.4.0
  # --
  webview_flutter_android: ^4.10.0
  webview_flutter_wkwebview: ^3.18.5
  webview_flutter_web: ^0.2.3+4
  # --
  webview_flutter: ^4.9.0  
  image_picker: ^1.2.0
  firebase_storage: ^13.0.0
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
