name: trackstatus_flutter
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4 
  cloud_firestore: ^4.17.2

  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  
  go_router: ^13.2.5

  font_awesome_flutter: '>= 4.7.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
