import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/notification_model.dart' as app_models;

class NotificationService {
  static final NotificationService _instance = NotificationService._internal();
  factory NotificationService() => _instance;
  NotificationService._internal();

  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging.instance;
  final AndroidNotificationChannel _channel = const AndroidNotificationChannel(
    'high_importance_channel',
    'High Importance Notifications',
    description: 'This channel is used for important notifications',
    importance: Importance.high,
  );

  late final FlutterLocalNotificationsPlugin localNotificationsPlugin =
      FlutterLocalNotificationsPlugin();

  // Initialize platform notifications
  Future<void> initializePlatformNotifications() async {
    // Initialize local notifications plugin
    await localNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(_channel);

    await localNotificationsPlugin.initialize(
      const InitializationSettings(
        android: AndroidInitializationSettings('@mipmap/ic_launcher'),
        iOS: DarwinInitializationSettings(), // สำหรับ iOS
      ),
    );
    
    // On iOS, ensure APNS token is properly initialized
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      try {
        String? apnsToken = await _firebaseMessaging.getAPNSToken();
        if (apnsToken != null) {
          print('APNS Token retrieved: $apnsToken');
        } else {
          print('APNS Token not available yet. This is normal during initial app startup.');
        }
      } catch (e) {
        print('Error getting APNS token: $e');
      }
    }
  }

  // Request notification permission
  Future<void> requestNotificationPermission() async {
    // Request permission for iOS
    NotificationSettings settings = await _firebaseMessaging.requestPermission(
      alert: true,
      announcement: true,
      badge: true,
      carPlay: true,
      criticalAlert: true,
      provisional: true,
      sound: true,
    );

    print('User granted permission: ${settings.authorizationStatus}');
  }

  // Handle notification stream
  void handleNotificationStream() {
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print('Received a message: ${message.notification?.title}');
      
      // Show local notification
      if (message.notification != null) {
        localNotificationsPlugin.show(
          0,
          message.notification!.title,
          message.notification!.body,
          NotificationDetails(
            android: AndroidNotificationDetails(
              _channel.id,
              _channel.name,
              channelDescription: _channel.description,
              importance: Importance.high,
              priority: Priority.high,
              ticker: 'ticker',
            ),
          ),
        );
      }
    });
  }

  /// Send push notification to a specific device token
  /// Note: In real applications, push notifications are typically sent from a server
  /// This function demonstrates how to format the notification data
  Future<void> sendPushNotification({
    required String deviceToken,
    required String title,
    required String body,
    Map<String, dynamic>? data,
  }) async {
    try {
      // In a real application, this would require calling a server endpoint
      // or using Firebase Admin SDK which only runs on the server
      print('Would send notification to device: $deviceToken');
      print('Title: $title');
      print('Body: $body');
      print('Data: $data');

      // For demonstration, we're logging the notification data
      // Actual implementation would involve making an HTTP request to Firebase Cloud Messaging
    } catch (e) {
      print('Error sending push notification: $e');
    }
  }

  final FirebaseAuth _auth = FirebaseAuth.instance;

  CollectionReference get notificationsCollection => FirebaseFirestore.instance.collection('notifications');

  /// Create a notification record in Firestore
  Future<String> createFirestoreNotification({
    required String title,
    required String body,
    required String type,
    required String senderId,
    required String senderName,
    required String recipientId,
    Map<String, dynamic>? payload,
  }) async {
    try {
      // Create a new notification instance
      final notification = app_models.Notification(
        id: '', // Will be auto-generated by Firestore
        title: title,
        body: body,
        type: type,
        senderId: senderId,
        senderName: senderName,
        recipientId: recipientId,
        timestamp: DateTime.now(),
        isRead: false,
        payload: payload,
      );

      // Add the notification to Firestore
      final docRef = await notificationsCollection.add(notification.toMap());
      
      // Return the ID of the created notification
      return docRef.id;
    } catch (e) {
      print('Error creating Firestore notification: $e');
      rethrow; // Rethrow the error so the caller can handle it
    }
  }

  // Get notifications for current user
  Stream<List<app_models.Notification>> getUserNotifications() {
    final user = _auth.currentUser;
    if (user == null) {
      return const Stream.empty();
    }

    return notificationsCollection
        .where('recipientId', isEqualTo: user.uid)
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => app_models.Notification.fromMap(doc.data() as Map<String, dynamic>))
          .toList();
    });
  }

  // Mark notification as read
  Future<void> markAsRead(String notificationId) async {
    try {
      await notificationsCollection.doc(notificationId).update({'isRead': true});
    } catch (e) {
      print('Error marking notification as read: $e');
    }
  }

  // Mark all notifications as read for current user
  Future<void> markAllAsRead() async {
    final user = _auth.currentUser;
    if (user == null) return;

    try {
      QuerySnapshot unreadNotifications = await notificationsCollection
          .where('recipientId', isEqualTo: user.uid)
          .where('isRead', isEqualTo: false)
          .get();

      for (var doc in unreadNotifications.docs) {
        await notificationsCollection.doc(doc.id).update({'isRead': true});
      }
    } catch (e) {
      print('Error marking all notifications as read: $e');
    }
  }
}